CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true

GPUS: [0]
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 6
PRINT_FREQ: 10

DATASET:
  DATASET: camvid
  ROOT: data/
  TEST_SET: 'list/camvid/test.lst'
  TRAIN_SET: 'list/camvid/trainval.lst'
  NUM_CLASSES: 11

MODEL:
  NAME: vm_hssnet
  NUM_OUTPUTS: 1
  PRETRAINED: "pretrained_weight/cityscapes/stdc_v2/city_test_2048x1024.pt"

LOSS:
  USE_OHEM: true
  OHEMTHRES: 0.7
  OHEMKEEP: 131072
  BALANCE_WEIGHTS: [0.4, 1.0]
  SB_WEIGHTS: 1.0

TRAIN:
  IMAGE_SIZE:
  - 960
  - 720
  BASE_SIZE: 960
  BATCH_SIZE_PER_GPU: 6
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 121
  RESUME: false
  OPTIMIZER: sgd
  LR: 0.005
  WD: 0.0005
  MOMENTUM: 0.9
  NESTEROV: false
  FLIP: true
  MULTI_SCALE: true
  IGNORE_LABEL: 255
  SCALE_FACTOR: 16

TEST:
  IMAGE_SIZE:
  - 960
  - 720
  BASE_SIZE: 960
  BATCH_SIZE_PER_GPU: 1
  FLIP_TEST: false
  MULTI_SCALE: false
  MODEL_FILE: ''
  OUTPUT_INDEX: 0
  OTHER_SCALE: false